# Site settings
site: Personal Blog
title: Personal Blog
keywords: Personal Blog, blog, yazılım geliştirme, siber güvenlik, programlama, c programlama dili
description: >-
  Hakan Torun Kişisel Blog Sitesi. Bilgisayar mühendisliği, yazılım geliştirme, siber güvenlik ve çeşitli konularda blog gönderilerine erişebilirsiniz.
lang: tr-TR
timezone:  Europe/Istanbul
repo: https://github.com/YiPianYe/yipianye.github.io # site repo [optional]
google_verify:      Q4Ewp22lX-Di13l6lh2oxChSmpGfBP0SPj8 # Put your Google Verification here
google_analytics:   UA-501526-19 # Put your Google Analytics code
discus-identifier: hakanio

# Author settings
author:
  name: Hakan Torun
  bio: Computer Engineer @pardinus <br> Founder @zaqa <br> Open Source /#linux
  picture: assets/images/hakan-torun.jpg 
  github: onepase # github username
  twitter: onepase # twitter username
  facebook: onepase # facebook username
  instagram: onepase # instagram username
  youtube: onepase # youtube username
  email: onepase[hirobot]gmail.com # email adress


# URL settings
url: "https://icp.me/" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 18
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
