# Site settings
site: 鸿博
title: HBw.Me
keywords: HBw.Me, Blog,MicroBlog， 
description: >-
   微型博客（MicroBlog），顾名思义，就是博客的微缩版，也即是博客的一种！
lang: utf-8
timezone:  Europe/Istanbul
repo: https://github.com/YiPianYe/ # site repo [optional]
# google_verify:      Q4Ewp22lX-DiRoBVzVVP13 # Put your Google Verification here
# google_analytics:   UA-5015 # Put your Google Analytics code
# discus-identifier: hakanio

# Author settings
author:
  name: 鸿博
  # bio
  bio: HB <br> MicroBlog <br> 微型博客（MicroBlog）博客的微缩版，也即是博客的一种！ <br> 
      
  # 头像切换
  picture: assets/images/xiaolian.png
 # picture: assets/images/h.png
 # picture: assets/images/b.png
 # picture: assets/images/hh.png
 # picture: assets/images/hhh.png
 # picture: assets/images/hhhh.png
 # picture: assets/images/xiaolian.png
  github: yipianye/hbwme # github username
  twitter:  # twitter username
  facebook:  # facebook username
  instagram:  # instagram username
  youtube:  # youtube username
  email: workgroupsme#gmail.com # email adress


# URL settings
url: "https://hbw.me" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 18
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
